version: '3.8'

services:
  # Nginx リバースプロキシ
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl  # SSL証明書用
      - static-content:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - yuutai-network
    restart: always

  # フロントエンド
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - static-content:/usr/share/nginx/html
    networks:
      - yuutai-network

  # バックエンド
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend/db:/app/backend/db
      - ./backend/cache:/app/backend/cache
    environment:
      - NODE_ENV=production
      - PORT=5001
    networks:
      - yuutai-network
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # スクレイピングはローカルで実行し、DBファイルをアップロードする方式に変更
  # 手順:
  # 1. ローカルで npm run setup を実行
  # 2. backend/db/yuutai.db をGCEにアップロード
  # 3. docker-compose exec backend chown nodejs:nodejs /app/backend/db/yuutai.db

networks:
  yuutai-network:
    driver: bridge

volumes:
  static-content:
    driver: local