version: '3.8'

services:
  # フロントエンド (Svelte)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:5001/api
    networks:
      - yuutai-network

  # バックエンド (Node.js API)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend/db:/app/backend/db
      - ./backend/cache:/app/backend/cache
    environment:
      - NODE_ENV=production
      - PORT=5001
    networks:
      - yuutai-network
    restart: unless-stopped

# スクレイピングはローカルで実行し、DBファイルをアップロードする方式
# 手順:
# 1. ローカルで npm run setup を実行
# 2. backend/db/yuutai.db をGCEにアップロード:
#    gcloud compute scp backend/db/yuutai.db yuutai-app:~/yuutai-investment-tool/backend/db/ --zone=us-central1-a
# 3. 権限を修正:
#    docker-compose exec backend chown nodejs:nodejs /app/backend/db/yuutai.db

networks:
  yuutai-network:
    driver: bridge

# volumes:
#   プロジェクトローカルのフォルダを直接マウントするため、
#   名前付きボリュームは使用しません